---
version: "2"
checks:
  file-lines:
    config:
      threshold: 2000
plugins:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseClassName:
        enabled: false
      Controversial/CamelCaseMethodName:
        enabled: false
      Controversial/CamelCasePropertyName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
      Controversial/Superglobals:
        enabled: false
      CleanCode/ElseExpression:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2,PHPCS,Zend"
  sonar-php:
    enabled: true
    config:
      tests_patterns:
        - tst/**
exclude_patterns:
  - "cfg/"
  - "css/"
  - "!css/privatebin.css"
  - "!css/noscript.css"
  - "!css/bootstrap/privatebin.css"
  - "js/"
  - "!js/privatebin.js"
  - "!js/common.js"
  - "!js/test/"
  - "vendor/"

