language: php
sudo: false
php:
  - 5.5
  - 5.6
  - 7.0
node_js:
  - "node"

before_script:
  - composer install -n
  - npm install -g mocha
  - cd js
  - npm install jsverify jsdom jsdom-global
  - cd ..

script:
  - cd tst && phpunit
  - cd ../js && mocha

after_script:
  - cd ..
  - vendor/bin/codacycoverage clover tst/log/coverage-clover.xml
  - vendor/bin/test-reporter --coverage-report tst/log/coverage-clover.xml
