language: php
sudo: false
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

# as this is a php project, node.js v4 (for JS unit testing) isn't installed
install:
  - if [ ! -d "$HOME/.nvm" ]; then mkdir -p $HOME/.nvm && curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | NVM_METHOD=script bash; fi
  - source ~/.nvm/nvm.sh && nvm install 4

before_script:
  - composer install -n
  - npm install -g mocha
  - cd js
  - npm install jsverify jsdom@9 jsdom-global@2
  - cd ..

script:
  - cd tst && ../vendor/bin/phpunit
  - cd ../js && mocha

after_script:
  - cd ..
  - vendor/bin/codacycoverage clover tst/log/coverage-clover.xml
  - vendor/bin/test-reporter --coverage-report tst/log/coverage-clover.xml

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.composer/cache/vcs
    - $HOME/.nvm
    - $HOME/.npm
    - js/node_modules
