language: php
sudo: false
php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer install -n

script:
  - cd tst && ../vendor/bin/phpunit

after_script:
  - ../vendor/bin/codacycoverage clover log/coverage-clover.xml
  - ../vendor/bin/test-reporter --coverage-report log/coverage-clover.xml
