language: php
sudo: false
php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer config -g github-oauth.github.com "$GITHUB_TOKEN"
  - composer install -n

script:
  - cd tst && ../vendor/bin/phpunit

after_script:
  - cd ..
  - vendor/bin/codacycoverage clover tst/log/coverage-clover.xml
  - vendor/bin/test-reporter --coverage-report tst/log/coverage-clover.xml
