language: php
sudo: false
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install -n

script:
  - cd tst && ../vendor/bin/phpunit

after_script:
  - vendor/bin/codacycoverage clover tst/log/coverage-clover.xml
