language: php
sudo: false
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install -n

script:
  - vendor/bin/phpunit tst

after_script:
  - php vendor/bin/codacycoverage clover tst/log/coverage-clover.xml
