version: '3'

services:
  privatebin:
    build: .
    ports:
      - "3000:80"
    volumes:
      - data:/var/www/html/data
      # Optionally mount a custom config file
      #- /srv/docker/privatebin/conf.php:/var/www/html/cfg/conf.php
    
volumes:
  data:

